image: stablebaselines/rl-baselines3-zoo-cpu:latest

# Recursive clone
variables:
  GIT_SUBMODULE_STRATEGY: recursive

type-check:
  script:
  - make type

pytest:
  script:
  # MKL_THREADING_LAYER=GNU to avoid MKL_THREADING_LAYER=INTEL incompatibility error
  - MKL_THREADING_LAYER=GNU make pytest
  coverage: '/^TOTAL.+?(\d+\%)$/'

check-trained-agents:
  script:
  # MKL_THREADING_LAYER=GNU to avoid MKL_THREADING_LAYER=INTEL incompatibility error
  - pip install pickle5  # Add support for pickle5 protocol
  - MKL_THREADING_LAYER=GNU make check-trained-agents

lint:
  script:
    - make check-codestyle
    - make lint
