image: stablebaselines/rl-baselines3-zoo-cpu:latest

# Recursive clone
variables:
  GIT_SUBMODULE_STRATEGY: recursive

type-check:
  script:
  # Install gSDE branch
  - pip install git+https://github.com/DLR-RM/stable-baselines3@sde
  - make type

pytest:
  script:
  - pip install git+https://github.com/DLR-RM/stable-baselines3@sde
  # MKL_THREADING_LAYER=GNU to avoid MKL_THREADING_LAYER=INTEL incompatibility error
  - MKL_THREADING_LAYER=GNU make pytest

lint:
  script:
    - make check-codestyle
    - make lint
