[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rl_zoo3"
description = "A Training Framework for Stable Baselines3 Reinforcement Learning Agents"
readme = "README.md"
authors = [{ name = "Antonin Raffin", email = "antonin.raffin@dlr.de" }]
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "reinforcement-learning-algorithms",
    "reinforcement-learning",
    "machine-learning",
    "gymnasium",
    "openai",
    "stable",
    "baselines",
    "sb3",
    "toolbox",
    "python",
    "data-science",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10"
dependencies = [
    "sb3_contrib>=2.9.0,<3.0",
    "gymnasium>=0.29.1,<2.0",
    "huggingface_sb3>=3.0,<4.0",
    "tqdm",
    "rich",
    "optuna>=3.0",
    "pyyaml>=5.1",
    "pytablewriter~=1.2",
    "shimmy~=2.0",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "rl_zoo3._version.__version__" }

[project.optional-dependencies]
# NOTE: rliable~=1.2.0 required arch<8.0, which is not compatible with pandas 3.x
plots = ["seaborn", "rliable~=1.2.0", "scipy~=1.10", "pandas>=2.2,<3"]
tests = [
    # for MuJoCo envs v4:
    "mujoco>=2.3,<4",
    # install parking-env to test HER
    "highway-env>=1.10.1,<1.11.0",
]
extras = [
    "gym==0.26.2",
    "stable-baselines3[extra,tests,docs]>=2.9.0,<3.0",
    "pybullet_envs_gymnasium>=0.6.0",
    # minigrid
    "cloudpickle>=2.2.1",
    # Optuna auto
    "optunahub>=0.2.0",
    # optuna plots:
    "plotly",
    # need to upgrade to gymnasium:
    # panda-gym~=3.0.1
    "wandb",
    "moviepy>=1.0.0",
    # box2d is handled same as Gymnasium's pyproject.toml
    "box2d==2.3.10; python_version < '3.14'",
    "box2d-py==2.3.8; python_version >= '3.14'",
    "swig==4.*; python_version >= '3.14'",
]

[project.urls]
Code = "https://github.com/DLR-RM/rl-baselines3-zoo"
Documentation = "https://rl-baselines3-zoo.readthedocs.io/en/master/"
Changelog = "https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/CHANGELOG.md"
Stable-Baselines3 = "https://github.com/DLR-RM/stable-baselines3"
RL-Zoo = "https://github.com/DLR-RM/rl-baselines3-zoo"
SBX = "https://github.com/araffin/sbx"

[project.scripts]
rl_zoo3 = "rl_zoo3.cli:main"

[tool.setuptools]
packages = ["rl_zoo3", "rl_zoo3.plots", "rl_zoo3.hyperparams"]

[tool.setuptools.package-dir]
"rl_zoo3.hyperparams" = "hyperparams"

[tool.setuptools.package-data]
rl_zoo3 = ["py.typed", "version.txt"]
"rl_zoo3.hyperparams" = ["*.yml"]

[tool.ruff]
# Same as Black.
line-length = 127
# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF"]
# Ignore explicit stacklevel`
ignore = ["B028"]

[tool.ruff.lint.per-file-ignores]
"./rl_zoo3/import_envs.py" = ["F401"]
# "./rl_zoo3/plots/plot_train.py"= ["E501"]


[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 127

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
exclude = """(?x)(
    tests/dummy_env/*$
  )"""

[tool.pytest.ini_options]
# Deterministic ordering for tests; useful for pytest-xdist.
env = [
	"PYTHONHASHSEED=0"
]

filterwarnings = [
    # Tensorboard warnings
    "ignore::DeprecationWarning:tensorboard",
    # Gym warnings
    "ignore::UserWarning:gym",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]

[tool.coverage.run]
disable_warnings = ["couldnt-parse"]
branch = false
omit = [
	"tests/*",
	"setup.py",
	"rl_zoo3/plots/*",
	"rl_zoo3/push_to_hub.py",
	"scripts/*",
]

[tool.coverage.report]
exclude_lines = [ "pragma: no cover", "raise NotImplementedError()", "if typing.TYPE_CHECKING:"]
