/***
 * This file was AUTOGENERATED by Stable Baselines3 Zoo
 * https://github.com/DLR-RM/rl-baselines3-zoo
 */
#include "baselines3_models/FILE_NAME.h"
#include "baselines3_models/preprocessing.h"
#ifdef EXPORT_PYBIND
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#endif

namespace baselines3_models {

CLASS_NAME::CLASS_NAME() : Predictor("MODEL_FNAME") {
  policy_type = POLICY_TYPE;
}

torch::Tensor CLASS_NAME::preprocess_observation(torch::Tensor &observation) {
  torch::Tensor result;
  PREPROCESS_OBSERVATION
  return result;
}

torch::Tensor CLASS_NAME::process_action(torch::Tensor &action) {
  torch::Tensor result;
  PROCESS_ACTION
  return result;
}

#ifdef EXPORT_PYBIND
namespace py = pybind11;

PYBIND11_MODULE(baselines3_py, m) {
  py::class_<CLASS_NAME>(m, "CLASS_NAME")
      .def(py::init())
      .def("predict", &CLASS_NAME::predict_vector);
}
#endif

} // namespace baselines3_models