name: "\U0001F4DA Documentation"
description: Report an issue related to RL Baselines3 Zoo documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        **Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.
        Please post your question on the [RL Discord](https://discord.com/invite/xhfNqQv), [Reddit](https://www.reddit.com/r/reinforcementlearning/) or [Stack Overflow](https://stackoverflow.com/) in that case.
  - type: textarea
    id: description
    attributes:
      label: 📚 Documentation
      description: A clear and concise description of what should be improved in the documentation.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
          required: true
