atari:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  policy: 'CnnPolicy'
  n_timesteps: !!float 1e7
  buffer_size: 1000000
  exploration_fraction: 0.1
  learning_rate: !!float 1e-4
  policy_kwargs: "dict(optimizer_class=th.optim.Adam)"
  learning_starts: 50000
  target_update_interval: 10000
  train_freq: 4
  exploration_final_eps: 0.05

CartPole-v1:
  n_timesteps: !!float 3e4
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  learning_starts: 10000

MountainCar-v0:
  n_timesteps: 100000
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  learning_starts: 5000
  buffer_size: 30000
  exploration_final_eps: 0.1

LunarLander-v2:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  learning_starts: 5000
  buffer_size: 50000
  exploration_final_eps: 0.05

Acrobot-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  learning_starts: 5000
  buffer_size: 50000
  exploration_final_eps: 0.02
