# === Real Robot envs
NeckGoalEnvRelativeSparse-v2:
  model_class: 'sac'
  # env_wrapper:
  #   - utils.wrappers.HistoryWrapper:
  #       horizon: 2
  #   - sb3_contrib.common.wrappers.TimeFeatureWrapper
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 100000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.02
  n_episodes_rollout: 1
  gradient_steps: -1
  train_freq: -1
  # 10 episodes of warm-up
  learning_starts: 1500
  use_sde_at_warmup: True
  use_sde: True
  sde_sample_freq: 64
  policy_kwargs: "dict(log_std_init=-2, net_arch=[256, 256])"
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  online_sampling: False

NeckGoalEnvRelativeDense-v2:
  model_class: 'sac'
  env_wrapper:
    - utils.wrappers.HistoryWrapperObsDict:
        horizon: 2
  #   - sb3_contrib.common.wrappers.TimeFeatureWrapper
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 200000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.02
  n_episodes_rollout: 1
  gradient_steps: -1
  train_freq: -1
  # 10 episodes of warm-up
  learning_starts: 1500
  use_sde_at_warmup: True
  use_sde: True
  sde_sample_freq: 64
  policy_kwargs: "dict(log_std_init=-2, net_arch=[256, 256])"
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  online_sampling: False

# DDPG hyperparams
#parking-v0:
#  n_timesteps: !!float 2e5
#  policy: 'MlpPolicy'
#  model_class: 'ddpg'
#  n_sampled_goal: 4
#  goal_selection_strategy: 'future'
#  buffer_size: 1000000
#  batch_size: 256
#  gamma: 0.95
#  learning_rate: !!float 1e-3
#  noise_type: 'normal'
#  noise_std: 0.2
#  policy_kwargs: "dict(net_arch=[256, 256, 256])"
#  online_sampling: True
#  max_episode_length: 100


parking-v0:
  n_timesteps: !!float 2e5
  policy: 'MlpPolicy'
  model_class: 'tqc'
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  batch_size: 2048
  gamma: 0.95
  learning_rate: !!float 1e-3
  tau: 0.05
  ent_coef: 0.01
  policy_kwargs: "dict(n_critics=1, net_arch=[256, 256, 256])"
  online_sampling: True
  max_episode_length: 100
  # normalize: True

# TD3 hyperparams, her paper
#parking-v0:
#  n_timesteps: !!float 2e5
#  policy: 'MlpPolicy'
#  model_class: 'td3'
#  n_sampled_goal: 4
#  goal_selection_strategy: 'future'
#  buffer_size: 1000000
#  batch_size: 256
#  gamma: 0.95
#  learning_rate: !!float 1e-3
#  noise_type: 'normal'
#  noise_std: 0.2
#  policy_kwargs: "dict(net_arch=[256, 256, 256])"
#  online_sampling: True
#  max_episode_length: 100


# Mujoco Robotic Env
# DDPG hyperparams
# FetchReach-v1:
#   n_timesteps: !!float 20000
#   policy: 'MlpPolicy'
#   model_class: 'ddpg'
#   n_sampled_goal: 4
#   goal_selection_strategy: 'future'
#   buffer_size: 1000000
#   batch_size: 256
#   gamma: 0.95
#   random_exploration: 0.3
#   actor_lr: !!float 1e-3
#   critic_lr: !!float 1e-3
#   noise_type: 'normal'
#   noise_std: 0.2
#   normalize_observations: true
#   normalize_returns: false
#   policy_kwargs: "dict(layers=[256, 256, 256])"
#   online_sampling: True


FetchSlide-v1:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  model_class: 'tqc'
  n_sampled_goal: 1
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  ent_coef: 'auto'
  batch_size: 1024
  gamma: 0.95
  tau: 0.005
  learning_rate: !!float 7e-4
  learning_starts: 1000
  train_freq: 1
  online_sampling: True
  policy_kwargs: "dict(net_arch=[256, 256, 256])"

FetchPush-v1:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  model_class: 'tqc'
  n_sampled_goal: 3
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  ent_coef: 0.01
  batch_size: 1024
  gamma: 0.95
  tau: 0.01
  learning_rate: !!float 7e-4
  learning_starts: 1000
  train_freq: 1
  online_sampling: True
  # normalize: "{'norm_obs': True, 'norm_reward': False}"
  # policy_kwargs: "dict(net_arch=[512, 512])"
  policy_kwargs: "dict(n_critics=1)"

# Tuned
# FetchPickAndPlace-v1:
#   n_timesteps: !!float 1e6
#   policy: 'MlpPolicy'
#   model_class: 'tqc'
#   n_sampled_goal: 4
#   goal_selection_strategy: 'future'
#   buffer_size: 1000000
#   ent_coef: 'auto'
#   batch_size: 2048
#   ent_coef: 0.01
#   gamma: 0.95
#   tau: 0.05
#   learning_rate: !!float 1e-3
#   learning_starts: 1000
#   train_freq: 1
#   online_sampling: True
#   policy_kwargs: "dict(net_arch=[256, 256, 256])"

FetchPickAndPlace-v1:
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  model_class: 'tqc'
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  batch_size: 2048
  gamma: 0.95
  learning_rate: !!float 1e-3
  tau: 0.05
  ent_coef: 0.01
  policy_kwargs: "dict(n_critics=1, net_arch=[256, 256, 256])"
  online_sampling: True
  max_episode_length: 100

# SAC hyperparams
FetchReach-v1:
  n_timesteps: !!float 20000
  policy: 'MlpPolicy'
  model_class: 'sac'
  n_sampled_goal: 4
  goal_selection_strategy: 'future'
  buffer_size: 1000000
  ent_coef: 'auto'
  batch_size: 256
  gamma: 0.95
  learning_rate: 0.001
  learning_starts: 1000
  online_sampling: True
  normalize: True


# TD3 hyperparams
# FetchReach-v1:
#   n_timesteps: !!float 25000
#   policy: 'MlpPolicy'
#   model_class: 'td3'
#   n_sampled_goal: 4
#   goal_selection_strategy: 'future'
#   buffer_size: 1000000
#   batch_size: 256
#   gamma: 0.95
#   learning_rate: 0.001
#   learning_starts: 1000
