## Custom envs
donkey-mountain-track-v0: &defaults
  # Normalize AE (+ the rest)
  normalize: "{'norm_obs': True, 'norm_reward': False}"
  env_wrapper:
    - gym.wrappers.time_limit.TimeLimit:
        max_episode_steps: 10000
    - ae.wrapper.AutoencoderWrapper
    - utils.wrappers.HistoryWrapper:
        horizon: 2
  callback:
    - utils.callbacks.ParallelTrainCallback:
        gradient_steps: 200
    - utils.callbacks.LapTimeCallback
  n_timesteps: !!float 2e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 200000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.02
  train_freq: 200
  gradient_steps: 256
  learning_starts: 500
  use_sde_at_warmup: True
  use_sde: True
  sde_sample_freq: 16
  policy_kwargs: "dict(log_std_init=-3, net_arch=[256, 256], n_critics=2, use_expln=True)"

donkey-circuit-launch-track-v0:
  <<: *defaults
