# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # cpu version of pytorch - faster to download
        pip install torch==1.11+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install pybullet==3.1.9
        pip install -r requirements.txt
        # Use headless version
        pip install opencv-python-headless
        # install parking-env to test HER (pinned so it works with gym 0.21)
        pip install highway-env==1.5.0
    - name: Type check
      run: |
        make type
    - name: Check codestyle
      run: |
        make check-codestyle
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make pytest
