# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      TERM: xterm-256color
      FORCE_COLOR: 1
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # Install Atari Roms
        pip install autorom
        wget https://gist.githubusercontent.com/jjshoots/61b22aefce4456920ba99f2c36906eda/raw/00046ac3403768bfe45857610a3d333b8e35e026/Roms.tar.gz.b64
        base64 Roms.tar.gz.b64 --decode &> Roms.tar.gz
        AutoROM --accept-license --source-file Roms.tar.gz

        # cpu version of pytorch - faster to download
        pip install torch==1.13.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu
        pip install pybullet==3.2.5
        # for v4 MuJoCo envs:
        pip install mujoco
        pip install -r requirements.txt
        # Use headless version
        pip install opencv-python-headless
        # install parking-env to test HER
        pip install highway-env==1.8.1
        pip install -e .
    - name: Lint with ruff
      run: |
        make lint
    - name: Check codestyle
      run: |
        make check-codestyle
    - name: Build doc
      run: |
        make doc
    - name: Type check
      run: |
        make type
      # skip pytype type check for python 3.11 (not supported)
      if: "!(matrix.python-version == '3.11')"
    - name: Test with pytest
      run: |
        make pytest
