# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      TERM: xterm-256color
      FORCE_COLOR: 1
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==65.5.0
        # cpu version of pytorch - faster to download
        pip install torch==1.11.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu
        pip install pybullet==3.2.5
        # for v4 MuJoCo envs:
        pip install mujoco
        pip install -r requirements.txt
        # Use headless version
        pip install opencv-python-headless
        pip install highway-env==1.7.1
        pip install -e .
    - name: Type check
      run: |
        make type
      # skip mypy type check for python3.7 (last forever for some reason)
      if: "!(matrix.python-version == '3.7')"
    - name: Check codestyle
      run: |
        make check-codestyle
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make pytest
